networks:
  event-management-network:
    # external: true
    driver: bridge

services:
  db2-event-management:
    image: ibmcom/db2
    container_name: db2-event-management
    restart: unless-stopped
    ports:
      - "51822:50000"
    environment:
      - DBNAME=EVENTS
      - DB2INST1_PASSWORD=123456
      - LICENSE=accept
      - PERSISTENT_HOME=true
    volumes:
      - event-management-db2-data:/database
    privileged: true
    networks:
      - event-management-network
    healthcheck:
      disable: true
      test: ["CMD", "/opt/ibm/db2/V11.5/bin/db2ping", "EVENTS"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s

volumes:
  event-management-db2-data: