-- Create EVENTS schema if it doesn't exist
CREATE SCHEMA EVENTS;

-- Schema EVENTS
SET CURRENT_PATH = EVENTS;

-- create users table
CREATE TABLE IF NOT EXISTS EVENTS.USERS
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    first_name  VARCHAR(255) NOT NULL,
    last_name   VARCHAR(255) NOT NULL UNIQUE
);

-- create events table
CREATE TABLE IF NOT EXISTS EVENTS.EVENTS
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(255) NOT NULL UNIQUE,
    location       VARCHAR(255) NOT NULL,
    start_date     TIMESTAMP    NOT NULL,
    end_date       TIMESTAMP    NOT NULL,
    description    VARCHAR(1000),
    type           VARCHAR(50)  NOT NULL
);

-- join tables
CREATE TABLE IF NOT EXISTS EVENTS.EVENT_PARTICIPANTS
(
    event_id       BIGINT NOT NULL,
    user_id        BIGINT NOT NULL,
    PRIMARY KEY (event_id, user_id),
    FOREIGN KEY (event_id) REFERENCES EVENTS (id),
    FOREIGN KEY (user_id) REFERENCES USERS (id)
);
